version: '2'

networks:
  whatsapp:
    driver: bridge

services:
  go-whatsapp-multidevice-gpt:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'dimaskiddo/go-whatsapp-multidevice-gpt:latest'
    container_name: 'go-whatsapp-multidevice-gpt'
    networks:
      - whatsapp
    env_file:
      - ./.env
    volumes:
      - ./dbs:/usr/app/go-whatsapp-multidevice-gpt/dbs
    restart: unless-stopped
